version: '3'

services:
  django:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: grafos_web
    volumes:
      - .:/app
    env_file:
      - ./.env
    ports:
      - "8080:8080"
