version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: grafos_web
    volumes:
      - .:/app
    env_file:
      - ./.env
    ports:
      - 8001:8001
      - 5678:5678
